name: Generate Snake Animation (Gruvbox)

# Need write permission to push generated files back to the repo
permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate snake svg (Gruvbox)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#d79921&color_dots=#504945,#bdae93,#ebdbb2,#fbf1c7

      - name: Show generated files (debug)
        run: |
          echo "=== dist contents ==="
          ls -la dist || true
          echo "=== file types ==="
          file dist/* || true

      - name: Commit & push 'dist' into 'output' branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git user for the commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create / switch to the output branch and commit changes
          git checkout -B output
          git add -A dist
          git commit -m "chore: update snake animation" || echo "No changes to commit"
          # Push (will fail and show the error in logs if permission / branch-protection blocks it)
          git push -u origin output --force