name: Generate Snake Animation

on:
  schedule:               # Run automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:      # Allow manual triggering
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: dhodgson615
          outputs: dist/snake.svg

      - name: Push generated snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
